// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fazmwvpyirjxqjxdmzvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhem13dnB5aXJqeHFqeGRtenZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NDAwMzUsImV4cCI6MjA2MzAxNjAzNX0.q-_3JZEasMEb8vOFZG0QR49ui0jbH7wpgZxezBDJMMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);